### ISSUE TITLE
Define fixed observation height for CoordinateOperation

### ISSUE THREAD

**Issue by kad-simonm** [OSGeo/PROJ-JNI#57]
To transform coordinates we use a `CoordinateOperation` that we create using the method `Proj.createFromUserInput` based on an OGC WKT2 transformation string.

For optimal accuracy of a 2D transformation, we want to specify a fixed observation height for the transformation. I can't find anything about this in the PROJ C API documentation. However, this option is offered by the [cct](https://proj.org/apps/cct.html) tool with a `-z` argument.

Is there a way to do this through PROJ-JNI?

**Comment by desruisseaux** [comment]
I didn't not looked at the `cct` source code. Do you know which C++ API (if any) it uses? PROJ-JNI uses the C++ API instead than the C one, so if there is a public C++ API for that functionality, we can check how to make it accessible.

**Comment by kad-simonm** [comment]
No, in CCT the fixed height seems to be added when parsing each coordinate line. This is not behind an API. I can of course also do something similar via PROJ-JNI. However, the `CoordinateOperation` we use expects a dimension of 2 as source. Could I use the `srcOffset` parameter for this in the `transform` method? If not then I have to see if I can adjust the OGC WKT2 string that we use so that the source dimension becomes 3.

**Comment by desruisseaux** [comment]
In a `transform(srcPts, srcOff, dstPts, dstOff, numPts)` call, the `srcOff` parameter does not specify the number of dimensions. it only specifies the index of the first value to use in the `srcPts` array. For transforming three-dimensional coordinates, the source and target CRS must be three-dimensional by construction. We can not add a third dimension at a later step because there is many kinds of vertical heights (ellipsoidal, geoidal, barometric, _etc._), so just adding a _z_ value is ambiguous. The vertical axis must be described with the CRS.

If you are using WKT 2, then yes, the ideal fix is to use the WKT for defining a 3 dimensional CRS. If the vertical axis is an ellipsoidal height, then it is relatively easy: just write 3 instead of 2 in the `CS` WKT element and add a third `AXIS` element. But if the height is of any kind other than ellipsoidal, then it is still possible but more complicated. We have to use a "Compound CRS" construct.

**Comment by kad-simonm** [comment]
Thanks for the explanation. I'm going to get started on customizing the WKT2.
