### ISSUE TITLE
longitude latitude order

### ISSUE THREAD

**Issue by davidraleigh** [OSGeo/PROJ-JNI#60]
I haven't looked at the proj4 jni since way back when it was still in the main repo.  I notice that it seems the order of longitude latitude has been flipped? Maybe I'm mistaken?

Here in the example for proj-jin you've got lat lon:
https://github.com/OSGeo/PROJ-JNI/blob/main/example/TransformPoints.java#L83

But in the old proj jni it was the opposite ((λ,φ) axis order):
https://github.com/OSGeo/PROJ/blame/5.2/jniwrap/README.md#L109

Did something change in proj? Or are the jni wrappers different? If I prefer x,y ordered data what files can I change to prevent myself from having to reorder my arrays?

**Comment by davidraleigh** [comment]
ooof. nevermind. I found [this](https://proj.org/usage/transformation.html#proj-4-x-5-x-paradigm):
> With PROJ 6, the order of coordinates for EPSG geographic coordinate reference systems is latitude first, longitude second.
That's got to be the stupidest change I've witnessed in an API. can't understand why they wanted that.

**Comment by desruisseaux** [comment]
Hello David. Actually the problem was in PROJ 4 which was not compliant with EPSG definitions. For example EPSG:4326 has always been (_latitude_, _longitude_) in EPSG database, and PROJ 4 doing otherwise was causing interoperability problems. It has been a very long debate in the geospatial community (not only PROJ). The conclusion was (with my own words, I do not have the exact OGC wording in mind):

> Comply with EPSG definition, or if not do not use the "EPSG" name; use another name at your choice.

Having PROJ 6 finally compliant with this rule improve situation **a lot** in the geospatial community at large. If nevertheless the (_longitude_, _latitude_) axis order is desired, the [PROJ.normalizeForVisualization(…)](https://osgeo.github.io/PROJ-JNI/org/osgeo/proj/Proj.html#normalizeForVisualization(org.opengis.referencing.operation.CoordinateOperation)) method can be invoked.
